In [1]:
import pandas as pd

In [5]:
info = {
    "Name" : ["Haseeb", "Habib", "Ali"],
    "Age" : [12,13,14],
    "CGPA" : [3.14,4.0,3.8]
}

df = pd.DataFrame(info)

print(type(df))
print(df.index)
print(df.columns)
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

     Name  Age  CGPA
0  Haseeb   12  3.14
1   Habib   13  4.00
2     Ali   14  3.80

In [7]:
## Creating dtaframes from list of lists

df = pd.DataFrame([["Haseeb", 19],["Habib", 20],["Danyal", 23]], columns = ["Name", "Age"])
df

     Name  Age
0  Haseeb   19
1   Habib   20
2  Danyal   23

In [10]:
## Crreating Dataframes from numpy arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr, columns = ["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6

In [12]:
## csv data 
df = pd.read_csv("employee_data.csv")
## Json data
## df = pd.read_json("filename.json")
## excel sheet
## df = pd.read_excel("filename.xlsx")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000