In [1]:
import pandas as pd

In [11]:
df = pd.DataFrame({
    "id" : [1,2,3],
    "Name" : ["Habib" , "Haseeb", "Danyal"]
})

df2 = pd.DataFrame({
    "id" : [4,5,6],
    "Name" : ["Ahmed" , "Ali", "Usman"]
})

pd.concat([df,df2]) 
pd.concat([df,df2], axis =1)

   id    Name  id   Name
0   1   Habib   4  Ahmed
1   2  Haseeb   5    Ali
2   3  Danyal   6  Usman

In [7]:
df

   id    Name
0   1   Habib
1   2  Haseeb
2   3  Danyal

In [6]:
df2

   id   Name
0   4  Ahmed
1   5    Ali
2   6  Usman