In [1]:
import pandas as pd

In [2]:
df_customers = pd.DataFrame({
    "customer_id": [1,2,3,4],
    "name": ["Habib" , "Haseeb" , "Danyal", "Ali"]
    

})

df_orders = pd.DataFrame({
    "order_id": [101,102,103,104],
    "customer_id": [2,1,4,5], 
    "amount": [250,120,130,180]
})

In [14]:
pd.merge(df_customers, df_orders, on = "customer_id") ## Inner join ##
pd.merge(df_customers, df_orders, on = "customer_id" , how = "left") ## Left join ##
pd.merge(df_customers, df_orders, on = "customer_id" , how = "right") ## right join ##
pd.merge(df_customers, df_orders, on = "customer_id" , how = "outer")

   customer_id    name  order_id  amount
0            1   Habib     102.0   120.0
1            2  Haseeb     101.0   250.0
2            3  Danyal       NaN     NaN
3            4     Ali     103.0   130.0
4            5     NaN     104.0   180.0

In [10]:
df_customers

   customer_id    name
0            1   Habib
1            2  Haseeb
2            3  Danyal
3            4     Ali

In [11]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     130
3       104            5     180